/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

/**
 *
 * @author BrayanLuis
 */
public class FormDialogAlumno extends javax.swing.JDialog {

    /**
     * Creates new form FormDialogAlumno
     */
    public FormDialogAlumno(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNombres = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombres.setText("jTextField1");
        txtNombres.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombres:"));
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 40));

        jTextField2.setText("jTextField2");
        jTextField2.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellidos:"));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 150, 50));

        jTextField3.setText("jTextField3");
        jTextField3.setBorder(javax.swing.BorderFactory.createTitledBorder("DNI:"));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 140, 40));

        jTextField4.setText("jTextField4");
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 140, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDialogAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDialogAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDialogAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDialogAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormDialogAlumno dialog = new FormDialogAlumno(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}

/*
1. JFrame → ventana principal setSize(900,600) Aquí no hay otro contenedor “padre” decidiendo el tamaño. El JFrame es la ventana principal del sistema operativo. Entonces: setSize() define el tamaño REAL. Y: setMinimumSize(...) evita que el usuario reduzca demasiado la ventana. 2. JPanel → contenedor interno El JPanel normalmente vive dentro de un layout: BorderLayout FlowLayout GridLayout Entonces el panel NO controla totalmente su tamaño. El layout le pregunta: “¿qué tamaño prefieres?” y por eso existe: preferredSize 3. JButton con BoxLayout BoxLayout sí mira mucho: preferredSize maximumSize minimumSize porque organiza componentes uno debajo de otro. Si no limitas tamaño: BoxLayout puede estirar el botón horizontalmente o verticalmente. Por eso: btn.setMaximumSize(...) sirve como “tope”. Idea teórica importante Cada layout manager interpreta tamaños distinto. BorderLayout Usa mucho: preferredSize de WEST/EAST. BoxLayout Usa: preferredSize maximumSize alignment GridLayout Ignora casi todos los tamaños y hace todo igual. Entonces No existe: “una única medida oficial”
¡Excelente resumen! Tu análisis teórico de cómo Java Swing maneja los tamaños es 100% correcto. Has capturado perfectamente la esencia de Swing: el Layout Manager manda, y cada uno tiene sus propias reglas de juego.
Aquí tienes un desglose estructurado para complementar y consolidar tus apuntes:
📌 Comportamiento de Tamaños por Layout
BorderLayout
NORTH / SOUTH: Respeta solo el preferredSize de la altura. Ignora el ancho.
EAST / WEST: Respeta solo el preferredSize del ancho. Ignora la altura.
CENTER: Ignora cualquier tamaño sugerido. Se estira para llenar todo el espacio restante.
FlowLayout
Respeta estrictamente el preferredSize de todos sus componentes.
Si la ventana se achica, los componentes "fluyen" a la siguiente línea.
BoxLayout
Intenta respetar el preferredSize.
Si hay espacio extra, estira los componentes hasta su maximumSize.
Si falta espacio, los encoge hasta su minimumSize.
Usa alignmentX y alignmentY para alinear los bordes.
GridLayout
Regla de oro: Ignora preferredSize, minimumSize y maximumSize.
Divide el espacio en partes exactamente iguales para todos los componentes.
💡 3 Buenas Prácticas Clave en Swing
Evita setSize() en componentes internos: Modificar el tamaño manualmente (setSize, setBounds) en componentes dentro de un contenedor con Layout Manager no funciona o causa errores visuales.
Usa pack() en el JFrame: En lugar de darle un tamaño fijo al JFrame con setSize(900, 600), puedes usar frame.pack(). Esto calcula automáticamente el tamaño óptimo de la ventana basándose en los preferredSize de los paneles internos.
Componentes invisibles en BoxLayout: Para dejar espacios en blanco en BoxLayout, no uses márgenes. Usa componentes invisibles de la clase Box:
Box.createRigidArea(new Dimension(0, 20)); (Espacio fijo)
Box.createVerticalGlue(); (Espacio elástico que empuja los componentes)
Si estás diseñando una interfaz específica, dime:
¿Qué tipo de pantalla estás construyendo? (Login, tabla de datos, menú...)
¿Qué Layouts estás combinando actualmente?
Puedo darte el código de ejemplo exacto para estructurar tu diseño de forma limpia.





se breve en entonces en jpanl borderlayout no impor el amximsize ni el minimum sizze solo el preferered size?
Sí, es exacto. En un JPanel con BorderLayout, el layout ignora por completo el maximumSize y el minimumSize de los componentes.
Solo le importa el preferredSize, y lo hace con reglas estrictas:
NORTH / SOUTH: Solo mira el alto (height) preferido. El ancho lo estira a la fuerza.
EAST / WEST: Solo mira el ancho (width) preferido. El alto lo estira a la fuerza.
CENTER: Ignora todo. Se estira sí o sí para llenar el espacio que sobre.
Para ajustar los tamaños en tu diseño actual, dime:
¿En qué zona (NORTH, CENTER, etc.) está fallando el tamaño?
¿Qué componente se está deformando o estirando de más?





pero porque
Porque BorderLayout fue diseñado bajo una filosofía de "llenar espacios" y no de "respetar límites". Su prioridad es que la ventana nunca tenga huecos vacíos al estirarse.
Funciona así por estas razones técnicas:
Algoritmo simple: Para calcular el diseño rápido, el layout solo pide un dato (preferredSize). Si tuviera que calcular mínimos y máximos de 5 zonas a la vez, el código interno sería ineficiente.
Zonas con roles fijos:
Las zonas NORTH/SOUTH están pensadas para barras de herramientas o menús. El layout asume que siempre deben ocupar todo el ancho disponible.
Las zonas EAST/WEST son para paneles laterales. El layout asume que siempre deben ocupar todo el alto disponible.
El CENTER es el área principal (como un editor de texto o un mapa). El layout asume que el usuario siempre querrá que esa zona crezca al máximo si la ventana se agranda.
Si el usuario estira la ventana, BorderLayout está obligado a agrandar los componentes. Si respetara el maximumSize, quedarían huecos vacíos y fondos grises en la ventana, lo cual se ve mal visualmente.
Para darte una solución rápida, dime:
¿Qué componente se está estirando y se ve mal?
¿Quieres que se quede de un tamaño fijo o que deje de deformarse?







*/